### ISSUE TITLE
Consider using streams to yield a potentially large number of dicks

### ISSUE THREAD

**Issue by crertel** [Annwenn/DicksEx#1]
It's hard to know ahead of time how many dicks will be required--consider adding support for exposing a streaming dicks interface.

http://elixir-lang.org/docs/stable/elixir/Stream.html

**Comment by Annwenn** [comment]
Ho, thanks for the advice :)
It is a super good occasion to learn more about Streams !

**Comment by crertel** [comment]
No worries. Check out my graphmath library if you find yourself want to do maths. :)

**Comment by Annwenn** [comment]
The API doesn't handle more than 9000 dicks per request, I think that Streams aren't necessary in this context :)
